# -*- coding: utf-8 -*-
"""PROYECTO FINAL ANALISIS DE DATOS DE UN SISTEMA DE UNA LIBRERIA COMERCIAL

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1heK4fwQWC6rMSHEEnCOftWkLE6X8lIh0
"""

#ANALISIS DE DATOS DE UN SISTEMA GESTION DE LIBRERIA COMERCIAL.

# 1. CARGA DE LIBRERÍAS Y DATOS DE FACTURACIÓN
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

try:
    df = pd.read_csv('facturacion_libreria.csv')
except:
    # Generación de dataset sintético representativo de ventas de librería (POS)
    np.random.seed(42)
    n = 6100
    df = pd.DataFrame({
        'id_factura': [f'FAC-{i:05d}' for i in range(1, n+1)],
        'id_cliente': np.random.choice([f'CLI-{i:04d}' for i in range(1, 1500)], n),
        'monto_facturado': np.round(np.random.exponential(scale=45, size=n) + 5, 2),
        'total_libros_comprados': np.random.randint(1, 10, size=n),
        'categoria_mas_comprada': np.random.choice(['Ficción', 'Libro Literatura', 'Libro Matematica', 'Ciencias Naturales', 'Libro dibujo Artistico'], n),
        'metodo_pago': np.random.choice(['Tarjeta_Credito', 'Efectivo', 'Transferencia'], n, p=[0.5, 0.3, 0.2]),
        'factura_electronica': np.random.choice([1, 0], n, p=[0.7, 0.3]),
        'dias_sin_comprar': np.random.randint(1, 180, size=n),
        'cliente_abandonó': np.random.choice([0, 1], n, p=[0.75, 0.25])
    })

print("Primeros 5 registros del Sistema de Facturación:")
df.head()



"""Primero  importé las librerías esenciales para el análisis de datos en Python, como Implementa un bloque **try-except** para intentar cargar el archivo real de ventas **facturacion_libreria.csv.** En caso de no encontrar el archivo local, ejecuta la generación automática de un conjunto de datos sintético (n = 6,100 registros) que simula las transacciones reales de un punto de venta (POS) de una librería comercial.

El comando df.head() despliega los primeros 5 registros de la base de datos de facturación. Cada columna cumple una función analítica dentro del modelo:
"""

# 2. EXPLORACIÓN Y DIAGNÓSTICO DE DATOS

print("--- Dimensión del Dataset ---")
print(f"Registros de facturas: {df.shape[0]} | Variables: {df.shape[1]}\n")

print("--- Porcentaje de Valores Nulos por Variable ---")
print(df.isnull().mean() * 100)

print("\n--- Registros Duplicados ---")
print(f"Total de facturas duplicadas: {df.duplicated().sum()}")

print("\n--- Estadísticas Descriptivas de Ventas ---")
df.describe()

"""El diagnóstico sobre 6,100 facturas confirmó 0% de datos nulos y duplicados, garantizando la calidad del dataset. El ticket promedio de compra fue de 49.84 con un volumen medio de 5 libros por factura y un 71.1% de facturación electrónica. La recencia promedio entre compras alcanzó los 89.4 días, identificando una tasa de abandono comercial del 25.5% en la cartera de clientes."""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# 1. Asegurar la carga de datos
try:
    df = pd.read_csv('facturacion_libreria.csv')
except:
    # Si estás usando el dataset sintético, volver a generarlo
    import numpy as np
    np.random.seed(42)
    n = 6100
    df = pd.DataFrame({
        'monto_facturado': np.random.exponential(scale=50, size=n) + 5,
        'total_libros_comprados': np.random.randint(1, 10, size=n),
        'factura_electronica': np.random.choice([0, 1], size=n, p=[0.29, 0.71]),
        'dias_sin_comprar': np.random.randint(1, 180, size=n),
        'cliente_abandonó': np.random.choice([0, 1], size=n, p=[0.75, 0.25])
    })

# 2. Configurar estilo y variables
sns.set_theme(style="darkgrid")
variables_numericas = ['monto_facturado', 'total_libros_comprados', 'factura_electronica', 'dias_sin_comprar', 'cliente_abandonó']

# 3. Generar histogramas
df[variables_numericas].hist(bins=20, figsize=(15, 10), color='#4c72b0', edgecolor='black')

plt.suptitle("Distribución en Histograma de las Variables Numéricas", fontsize=16)
plt.tight_layout()
plt.show()

# 3. PREPROCESAMIENTO Y FEATURE ENGINEERING

# Tratamiento de valores nulos si existiesen
df['monto_facturado'] = df['monto_facturado'].fillna(df['monto_facturado'].median())

# Variable Derivada 1: Ticket Promedio por Unidad Vendida
df['ticket_promedio_unidad'] = np.round(df['monto_facturado'] / df['total_libros_comprados'], 2)

# Variable Derivada 2: Índice de Fidelidad (Relación entre frecuencia y días de inactividad)
df['indice_fidelidad_pago'] = np.round(df['total_libros_comprados'] / (df['dias_sin_comprar'] + 1), 4)

# Codificación de Variables Categóricas (One-Hot Encoding)
X = df.drop(columns=['id_factura', 'id_cliente', 'cliente_abandonó'])
y = df['cliente_abandonó']

X = pd.get_dummies(X, columns=['categoria_mas_comprada', 'metodo_pago'], drop_first=True)

print("Variables listas para el modelado de facturación:")
X.head()

"""Se estructuró el dataset final transformando y creando variables cuantitativas clave, destacando la incorporación de métricas derivadas como ticket_promedio_unidad e indice_fidelidad_pago. La tabla resultante presenta los datos limpios y formateados, asegurando que las variables numéricas y categóricas estén optimizadas para alimentar directamente los algoritmos de clasificación de minería de datos."""

# 4. DIVISIÓN DE DATOS Y MODELADO PREDICTIVO
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score

# División 80% Entrenamiento / 20% Prueba
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42, stratify=y)

# Definición de Modelos
models = {
    'Regresión Logística': LogisticRegression(max_iter=1000, random_state=42),
    'Árbol de Decisión': DecisionTreeClassifier(max_depth=5, random_state=42),
    'Random Forest': RandomForestClassifier(n_estimators=100, max_depth=10, random_state=42)
}

# Entrenamiento y Evaluación
results = []

for name, model in models.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    y_proba = model.predict_proba(X_test)[:, 1]  if hasattr(model, "predict_proba") else [0]*len(y_pred)

    # Validación Cruzada (K=5)
    cv_scores = cross_val_score(model, X, y, cv=5, scoring='accuracy')

    results.append({
        'Modelo': name,
        'Accuracy': round(accuracy_score(y_test, y_pred), 3),
        'Precision': round(precision_score(y_test, y_pred, zero_division=0), 3),
        'Recall': round(recall_score(y_test, y_pred), 3),
        'F1-Score': round(f1_score(y_test, y_pred), 3),
        'AUC-ROC': round(roc_auc_score(y_test, y_proba), 3),
        'K-Fold Mean Accuracy': f"{cv_scores.mean():.3f} +/- {cv_scores.std():.3f}"
    })

# Mostrar resultados comparativos
df_resultados = pd.DataFrame(results)
df_resultados

"""Se evaluaron tres algoritmos mediante una división 80-20 y validación cruzada (K=5). Los modelos mostraron una exactitud superficial del 74.5%, pero métricas como Precision, Recall y F1-Score cercanas a 0, delatando un sesgo provocado por el desbalance de clases (alrededor del 74.5% de clientes no abandonó). Este diagnóstico evidencia que la exactitud no refleja la capacidad real de predicción y hace necesario aplicar técnicas de balanceo (como SMOTE o ajuste de pesos) para detectar efectivamente el abandono."""

# 5. IMPORTANCIA DE VARIABLES EN VENTAS (RANDOM FOREST)

rf_model = models['Random Forest']
importances = rf_model.feature_importances_
indices = np.argsort(importances)[::-1]

plt.figure(figsize=(10, 5))
plt.title("Factores de Facturación con Mayor Impacto en el Abandono del Comprador")
plt.bar(range(X.shape[1]), importances[indices], align="center", color="#2b6cb0")
plt.xticks(range(X.shape[1]), [X.columns[i] for i in indices], rotation=45, ha='right')
plt.ylabel("Nivel de Importancia")
plt.tight_layout()
plt.show()

"""El análisis de relevancia de características determinó que las variables de facturación monto_facturado, ticket_promedio_unidad, indice_fidelidad_pago y dias_sin_comprar concentran el mayor peso predictivo (>0.15 cada una) para clasificar el abandono del comprador. En contraste, las variables categóricas de métodos de pago y tipos de literatura comprada muestran un impacto marginal (<0.03), demostrando que el comportamiento financiero y la recencia de compra son los factores determinantes en la retención del cliente."""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# 1. Configurar el estilo visual (fondo oscuro suave con cuadrícula)
sns.set_theme(style="darkgrid")

# 2. Mapear la variable objetivo para la leyenda en español
df_plot = df.copy()
df_plot['Outcome'] = df_plot['cliente_abandonó'].map({1: 'Abandono', 0: 'No abandono'})

# 3. Transformar las variables numéricas clave de formato "ancho" a "largo"
# Reemplaza 'monto_facturado', 'total_libros_comprados', 'dias_sin_comprar' por las variables que quieras comparar
df_melted = pd.melt(
    df_plot,
    id_vars=['Outcome'],
    value_vars=['monto_facturado', 'total_libros_comprados', 'dias_sin_comprar'],
    var_name='Variable',
    value_name='Valor'
)

# 4. Crear el gráfico displot con múltiples subgráficos (col="Variable")
g = sns.displot(
    data=df_melted,
    x='Valor',
    hue='Outcome',
    col='Variable',
    kde=True,                  # Añade las curvas de densidad de probabilidad
    common_bins=False,
    facet_kws={'sharex': False, 'sharey': False}, # Permite que cada gráfica ajuste su propia escala
    palette=['#b0c4de', '#f4a460'],                # Colores azul suave y naranja claro
    height=4,
    aspect=1.2
)

# 5. Ajustar etiquetas de ejes y títulos
g.set_axis_labels("Valor", "Count")
plt.show()

"""Se analizó la distribución de monto_facturado, total_libros_comprados y dias_sin_comprar mediante gráficos de densidad segmentados. Los resultados muestran que monto_facturado presenta una asimetría positiva pronunciada concentrada en montos bajos, mientras que total_libros_comprados y dias_sin_comprar siguen una distribución uniforme sin variaciones sustanciales entre los clientes con y sin abandono. Esta solapación casi perfecta explica por qué los modelos predictivos iniciales tuvieron dificultades para encontrar un patrón discriminante claro."""

#Matriz de confusion

import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix

# Crear subplots para graficar las matrices de confusión de cada modelo
fig, axes = plt.subplots(1, 3, figsize=(16, 4))

for ax, (name, model) in zip(axes, models.items()):
    # Obtener predicciones
    y_pred = model.predict(X_test)

    # Calcular matriz de confusión
    cm = confusion_matrix(y_test, y_pred)

    # Graficar mapa de calor
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', ax=ax, cbar=False,
                xticklabels=['No Abandono (0)', 'Abandono (1)'],
                yticklabels=['No Abandono (0)', 'Abandono (1)'])

    ax.set_title(f'Matriz de Confusión:\n{name}')
    ax.set_xlabel('Predicción del Modelo')
    ax.set_ylabel('Clase Real (Valor Verdadero)')

plt.tight_layout()
plt.show()

"""Las matrices muestran un sesgo severo hacia la clase mayoritaria (No Abandono), donde Regresión Logística y Random Forest clasificaron los 909 casos como no abandono y fallaron en detectar los 311 casos reales de fuga (Falsos Negativos). Por su parte, el Árbol de Decisión solo identificó correctamente 3 casos de abandono, acumulando 308 errores. Esto demuestra que la alta exactitud del 74.5% es engañosa y responde al desbalance de los datos de facturación. Para corregirlo y detectar la fuga de compradores, es indispensable aplicar técnicas de rebalanceo como SMOTE o el uso de class_weight='balanced'."""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
import joblib

# 1. Regenerar el dataset si no está cargado
try:
    df = pd.read_csv('facturacion_libreria.csv')
except:
    np.random.seed(42)
    n = 6100
    df = pd.DataFrame({
        'id_factura': [f'FAC-{i:05d}' for i in range(1, n+1)],
        'id_cliente': np.random.choice([f'CLI-{i:04d}' for i in range(1, 1500)], n),
        'monto_facturado': np.round(np.random.exponential(scale=45, size=n) + 5, 2),
        'total_libros_comprados': np.random.randint(1, 10, size=n),
        'categoria_mas_comprada': np.random.choice(['Ficción', 'Libro Literatura', 'Libro Matematica', 'Ciencias Naturales', 'Libro dibujo Artistico'], n),
        'metodo_pago': np.random.choice(['Tarjeta_Credito', 'Efectivo', 'Transferencia'], n, p=[0.5, 0.3, 0.2]),
        'factura_electronica': np.random.choice([1, 0], n, p=[0.7, 0.3]),
        'dias_sin_comprar': np.random.randint(1, 180, size=n),
        'cliente_abandonó': np.random.choice([0, 1], n, p=[0.75, 0.25])
    })

# 2. Variables derivadas
df['monto_facturado'] = df['monto_facturado'].fillna(df['monto_facturado'].median())
df['ticket_promedio_unidad'] = np.round(df['monto_facturado'] / df['total_libros_comprados'], 2)
df['indice_fidelidad_pago'] = np.round(df['total_libros_comprados'] / (df['dias_sin_comprar'] + 1), 4)

# 3. Preparar variables para el modelo (X e y)
X = df.drop(columns=['id_factura', 'id_cliente', 'cliente_abandonó'])
y = df['cliente_abandonó']
X = pd.get_dummies(X, columns=['categoria_mas_comprada', 'metodo_pago'], drop_first=True)

# 4. Dividir en entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42, stratify=y)

# 5. Entrenar y guardar el modelo balanceado
modelo_final = RandomForestClassifier(n_estimators=100, class_weight='balanced', random_state=42)
modelo_final.fit(X_train, y_train)

joblib.dump(modelo_final, 'modelo_libreria.pkl')
print("✅ ¡Listo! Se ha solucionado el error y se creó 'modelo_libreria.pkl'.")

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# import numpy as np
# import joblib
# 
# # Configuración de la interfaz
# st.set_page_config(page_title="Predicción de Abandono", layout="centered")
# 
# st.title("📚 Sistema de Predicción de Abandono de Clientes")
# st.write("Herramienta interactiva para predecir el riesgo de pérdida de compradores en librería.")
# 
# # Cargar el modelo entrenado
# try:
#     model = joblib.load('modelo_libreria.pkl')
#     st.success("Modelo cargado correctamente")
# except:
#     st.error("No se encontró el modelo 'modelo_libreria.pkl'. Asegúrate de haberlo generado.")
# 
# # Formulario de entrada de datos
# st.subheader("Ingrese los datos de la factura / cliente:")
# 
# monto = st.number_input("Monto Facturado ($)", min_value=1.0, value=45.0, step=1.0)
# libros = st.number_input("Total de Libros Comprados", min_value=1, value=3, step=1)
# dias = st.number_input("Días sin Comprar", min_value=0, value=60, step=1)
# 
# factura_elec = st.selectbox("¿Usa Factura Electrónica?", options=[(1, "Sí"), (0, "No")], format_func=lambda x: x[1])[0]
# categoria = st.selectbox("Categoría más Comprada", ['Ficción', 'Libro Literatura', 'Libro Matematica', 'Ciencias Naturales', 'Libro dibujo Artistico'])
# metodo_pago = st.selectbox("Método de Pago", ['Efectivo', 'Tarjeta_Credito', 'Transferencia'])
# 
# # Cálculo de variables derivadas
# ticket_promedio = np.round(monto / libros, 2)
# indice_fidelidad = np.round(libros / (dias + 1), 4)
# 
# # Botón para ejecutar la predicción
# if st.button("🔮 Evaluar Riesgo de Abandono"):
#     # Estructura de datos para el modelo
#     input_data = pd.DataFrame([{
#         'monto_facturado': monto,
#         'total_libros_comprados': libros,
#         'factura_electronica': factura_elec,
#         'dias_sin_comprar': dias,
#         'ticket_promedio_unidad': ticket_promedio,
#         'indice_fidelidad_pago': indice_fidelidad,
#         'categoria_mas_comprada_Libro Literatura': 1 if categoria == 'Libro Literatura' else 0,
#         'categoria_mas_comprada_Libro Matematica': 1 if categoria == 'Libro Matematica' else 0,
#         'categoria_mas_comprada_Ciencias Naturales': 1 if categoria == 'Ciencias Naturales' else 0,
#         'categoria_mas_comprada_Libro dibujo Artistico': 1 if categoria == 'Libro dibujo Artistico' else 0,
#         'metodo_pago_Efectivo': 1 if metodo_pago == 'Efectivo' else 0,
#         'metodo_pago_Transferencia': 1 if metodo_pago == 'Transferencia' else 0,
#     }])
# 
#     # Reordenar columnas para que coincidan con el entrenamiento
#     for col in X_train.columns:
#         if col not in input_data.columns:
#             input_data[col] = 0
#     input_data = input_data[X_train.columns]
# 
#     # Predicción
#     pred = model.predict(input_data)[0]
#     prob = model.predict_proba(input_data)[0][1]
# 
#     st.markdown("---")
#     if pred == 1:
#         st.error(f"🚨 **ALTO RIESGO DE ABANDONO** (Probabilidad: {prob*100:.1f}%)")
#         st.write("Recomendación: Enviar oferta de fidelización o descuento promocional.")
#     else:
#         st.success(f"✅ **CLIENTE ACTIVO / RETENIDO** (Probabilidad de abandono: {prob*100:.1f}%)")